name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019, ubuntu-18.04]

    steps:
      - name: check out git repository
        uses: actions/checkout@v1

      - name: install node.js, npm and yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        run: |
          yarn test

      - name: build
        run: yarn run build

      - name: dist
        run: yarn run dist

      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: dist


# Failing beacuse virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
